import type { GCMaterial } from "../types";

export const MOCK_MATERIALS: GCMaterial[] = [
  {
    id: "mat-001",
    name: "EcoCrete 30% Slag Blend",
    category: "Concrete",
    manufacturer: "HeidelbergMaterials",
    gwpPerUnit: 185,
    gwpUnit: "m³",
    materialCreditScore: 82,
    certifications: ["EPD Verified", "LEED Credit"],
    isVerified: true,
  },
  {
    id: "mat-002",
    name: "Reinforced Concrete C30/37",
    category: "Concrete",
    manufacturer: "Holcim",
    gwpPerUnit: 310,
    gwpUnit: "m³",
    materialCreditScore: 44,
    isVerified: true,
  },
  {
    id: "mat-003",
    name: "CrossLam CLT 5-ply",
    category: "Timber",
    manufacturer: "Binderholz",
    gwpPerUnit: -510,
    gwpUnit: "m³",
    materialCreditScore: 95,
    certifications: ["FSC", "EPD Verified", "PEFC"],
    isVerified: true,
  },
  {
    id: "mat-004",
    name: "S355 Structural Steel — 30% Recycled",
    category: "Steel",
    manufacturer: "ArcelorMittal",
    gwpPerUnit: 1020,
    gwpUnit: "tonne",
    materialCreditScore: 68,
    certifications: ["EPD Verified"],
    isVerified: true,
  },
  {
    id: "mat-005",
    name: "S355 Virgin Structural Steel",
    category: "Steel",
    manufacturer: "Tata Steel",
    gwpPerUnit: 1650,
    gwpUnit: "tonne",
    materialCreditScore: 31,
    isVerified: false,
  },
  {
    id: "mat-006",
    name: "Rock Wool Slab RW 140",
    category: "Insulation",
    manufacturer: "ROCKWOOL",
    gwpPerUnit: 1.4,
    gwpUnit: "m²",
    materialCreditScore: 77,
    certifications: ["EPD Verified", "Cradle to Cradle"],
    isVerified: true,
  },
  {
    id: "mat-007",
    name: "EPS Grey Insulation 120mm",
    category: "Insulation",
    manufacturer: "Knauf",
    gwpPerUnit: 4.2,
    gwpUnit: "m²",
    materialCreditScore: 52,
    isVerified: true,
  },
  {
    id: "mat-008",
    name: "Extruded Aluminium Profile — 75% Recycled",
    category: "Aluminum",
    manufacturer: "Hydro",
    gwpPerUnit: 3.4,
    gwpUnit: "kg",
    materialCreditScore: 88,
    certifications: ["REDUXA 4.0", "EPD Verified"],
    isVerified: true,
  },
  {
    id: "mat-009",
    name: "Float Glass 6mm",
    category: "Glass",
    manufacturer: "Pilkington",
    gwpPerUnit: 8.8,
    gwpUnit: "m²",
    materialCreditScore: 58,
    isVerified: true,
  },
  {
    id: "mat-010",
    name: "Gypsum Board 12.5mm Eco",
    category: "Gypsum",
    manufacturer: "Knauf",
    gwpPerUnit: 1.9,
    gwpUnit: "m²",
    materialCreditScore: 71,
    certifications: ["EPD Verified"],
    isVerified: true,
  },
  {
    id: "mat-011",
    name: "Clay Brick — Low-Carbon Kiln",
    category: "Masonry",
    manufacturer: "Wienerberger",
    gwpPerUnit: 0.22,
    gwpUnit: "unit",
    materialCreditScore: 65,
    certifications: ["EPD Verified"],
    isVerified: true,
  },
  {
    id: "mat-012",
    name: "Glulam GL24h",
    category: "Timber",
    manufacturer: "Schilliger Holz",
    gwpPerUnit: -620,
    gwpUnit: "m³",
    materialCreditScore: 91,
    certifications: ["FSC", "EPD Verified"],
    isVerified: true,
  },
  {
    id: "mat-013",
    name: "EPDM Roofing Membrane 1.5mm",
    category: "Roofing",
    manufacturer: "Firestone",
    gwpPerUnit: 3.1,
    gwpUnit: "m²",
    materialCreditScore: 60,
    isVerified: true,
  },
  {
    id: "mat-014",
    name: "Alkali-Activated Concrete (Geopolymer)",
    category: "Concrete",
    manufacturer: "Wagners",
    gwpPerUnit: 95,
    gwpUnit: "m³",
    materialCreditScore: 90,
    certifications: ["EPD Verified", "Innovation Credit"],
    isVerified: true,
  },
  {
    id: "mat-015",
    name: "LVL Kerto-S 45mm",
    category: "Timber",
    manufacturer: "Metsä Wood",
    gwpPerUnit: -480,
    gwpUnit: "m³",
    materialCreditScore: 87,
    certifications: ["FSC", "EPD Verified", "PEFC"],
    isVerified: true,
  },
];

export const MOCK_SWAPS: Record<string, GCMaterial[]> = {
  "mat-002": [MOCK_MATERIALS[0], MOCK_MATERIALS[13]],
  "mat-004": [MOCK_MATERIALS[3]],
  "mat-006": [MOCK_MATERIALS[5]],
  "mat-001": [MOCK_MATERIALS[13]],
};
